package com.example.core.domain.validation

import com.example.core.domain.capability.CapabilityRegistry
import com.example.core.domain.capability.StructuredIntent
import com.example.core.domain.error.ArishException

/**
 * Validates structured intents generated by LLM reasoning before mapping to plan.
 */
object IntentValidator {

    fun validate(intent: StructuredIntent) {
        if (intent.intentName.isBlank()) {
            throw ArishException.SchemaValidationException("intentName", "Intent name cannot be blank")
        }
        if (intent.confidence < 0.3f && !intent.requiresClarification) {
            throw ArishException.SchemaValidationException(
                "confidence",
                "Intent confidence (${intent.confidence}) is below minimum threshold (0.3) without requesting clarification"
            )
        }
        // Verify capability exists in registry
        val capability = CapabilityRegistry.find(intent.capabilityId)
            ?: throw ArishException.UnknownCapabilityException("Capability '${intent.capabilityId}' is not registered in CapabilityRegistry")
    }
}
